name: Build VoidLink IPA

on:
  workflow_dispatch:

jobs:
  build:
    name: Build VoidLink IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: "git submodule update --init --recursive"

      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build VoidLink
        run: |
          xcodebuild clean build \
            -scheme VoidLink \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED="NO" \
            CODE_SIGNING_ALLOWED="NO" \
            CODE_SIGN_ENTITLEMENTS="" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CONFIGURATION_BUILD_DIR="$PWD/build/Output"
          
          mkdir -p ./build/IPA/Payload
          cp -r ./build/Output/VoidLink.app ./build/IPA/Payload/VoidLink.app
          cd ./build/IPA && zip -r ../VoidLink.ipa ./Payload && cd ../..

      - name: Upload VoidLink IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VoidLink.ipa
          path: build/VoidLink.ipa
